[package]
name = "test_faers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faer = "0.19.1"
num-complex = "0.4.6"
nalgebra = "0.32.3"
num = "0.4.3"

[profile.dev.package.faer]
opt-level = 3